version: "3.8"

services:
  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - service_db

  product_service:
#    build:
#      context: ./product
#      dockerfile: Dockerfile
    build: ./product
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://db:27017/Gross_inventory
    networks:
      - service_db
    depends_on:
      - db
#      start after the depended service.!

  cart_service:
    build: ./cart
    ports:
      - "8081:8081"
    environment:
      - spring.data.mongodb.uri=mongodb://db:27017/Gross_inventory
    networks:
      - service_db
    depends_on:
      - db

  user-management_service:
    build: ./user-management
    ports:
      - "8082:8082"
    environment:
      - spring.data.mongodb.uri=mongodb://db:27017/Gross_inventory
      - secret=0ce62924a2ed57b5af99840366b2db54b5057a3d12e943bfcae51a6d04bac6f5
    networks:
      - service_db
    depends_on:
      - db

  gateway_service:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - ./gateway/src/main/resources/application.yml
    networks:
      - service_db
    depends_on:
      - db


networks:
  service_db:
    driver: bridge
#    default network driver!

volumes:
  db_data:

# for reference
# class version = java version
#  49 = Java 5
#  50 = Java 6
#  51 = Java 7
#  52 = Java 8
#  53 = Java 9
#  54 = Java 10
#  55 = Java 11
#  56 = Java 12
#  57 = Java 13
#  58 = Java 14
#  59 = Java 15
#  60 = Java 16
#  61 = Java 17
#  62 = Java 18
#  63 = Java 19
#  64 = Java 20
#  65 = Java 21