spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-management
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
            - id: product
              uri: http://localhost:8082
              predicates:
                - Path=/inventory/**
            - id: cart
              uri: http://localhost:8083
              predicates:
                - Path=/cart/**
server:
  port: 8080
