spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:8080/
          Predicates:
            - Path=/inventory/**
server:
  port: 8083