spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product
          uri: http://localhost:80801
          Predicates:
            - Path=/inventory/**
server:
  port: 8083