spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product
              uri: http://localhost:8080
              predicates:
                - Path=/inventory/**
            - id: user-management
              uri: http://localhost:8082
              predicates:
                - Path=/auth/**
server:
  port: 8083